"""
Shared Agent State — the single Pydantic model every LangGraph node reads and writes.

This is the contract between all internal modules. Get this right early —
every node in the workflow depends on this shape.

Note: LangGraph's StateGraph expects TypedDict by default.
We define a Pydantic model for validation and use a TypedDict adapter
for LangGraph compatibility.
"""

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field
from typing_extensions import TypedDict


# ---------------------------------------------------------------------------
# Pydantic model — used for validation, serialization, API responses
# ---------------------------------------------------------------------------

class AgentState(BaseModel):
    """Complete state object carried through the LangGraph workflow.

    Every node reads from and writes to this state. Fields are populated
    progressively as the graph executes:

        START → intent_parser (parsed_intent, entities)
              → planner (execution_plan)
              → executor (validates real analytics evidence is present)
              → explainer (explanation)
              → recommender (recommendation)
              → END

    The real analytics evidence (validation, rule_result, ml_result,
    risk_assessment, graph_metrics) is computed once, upfront, by
    investigation_service.run_investigation() and passed in via the initial
    state — the graph reasons over it, it does not recompute it.
    """

    # --- Input ---
    user_query: str = Field(
        ...,
        description="Original natural-language AML query from the user",
    )
    filters: dict[str, Any] = Field(
        default_factory=dict,
        description="Optional filters (date range, country, customer ID, etc.)",
    )

    # --- Intent Parsing (Phase 4) ---
    parsed_intent: Optional[dict[str, Any]] = Field(
        default=None,
        description=(
            "Structured intent extracted from the query. Keys include: "
            "intent, aml_pattern, transaction_type, threshold_amount"
        ),
    )
    entities: dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "Entities extracted via rule-based parsing: "
            "customer_ids, amounts, dates, country_codes"
        ),
    )

    # --- Execution Planning (Phase 5) ---
    execution_plan: list[str] = Field(
        default_factory=list,
        description=(
            "Ordered list of tool names to execute. "
            "e.g. ['run_eda', 'generate_features', 'detect_rules', 'detect_anomalies', 'calculate_risk']"
        ),
    )

    # --- Real Analytics Evidence ---
    # Populated by the caller (investigation_service.run_investigation) before
    # the graph is invoked. These are the dataclass outputs of the real
    # `analytics` pipeline (validation, rule engine, ML inference, risk
    # fusion, graph analytics) — the graph reasons over this evidence rather
    # than recomputing fraud detection itself.
    validation: Optional[Any] = Field(
        default=None, description="analytics.data.validator.ValidationReport"
    )
    rule_result: Optional[Any] = Field(
        default=None, description="analytics.interfaces.RuleResult"
    )
    ml_result: Optional[Any] = Field(
        default=None, description="analytics.ml.schemas.MLResult"
    )
    risk_assessment: Optional[Any] = Field(
        default=None, description="analytics.interfaces.RiskAssessment"
    )
    graph_metrics: Optional[Any] = Field(
        default=None, description="analytics.graph.schemas.GraphMetrics"
    )

    # --- Explanation (Phase 8) ---
    explanation: Optional[str] = Field(
        default=None,
        description="Human-readable compliance narrative generated by the Explainer agent",
    )

    # --- Recommendation (Phase 9) ---
    recommendation: Optional[str] = Field(
        default=None,
        description="Action recommendation: Monitor / Review / Escalate / Report",
    )

    # --- Observability ---
    trace: list[str] = Field(
        default_factory=list,
        description="Audit trail of node executions for demo and debugging",
    )
    errors: list[str] = Field(
        default_factory=list,
        description="Non-fatal errors encountered during execution (graceful degradation)",
    )


# ---------------------------------------------------------------------------
# TypedDict adapter — LangGraph's StateGraph needs this
# ---------------------------------------------------------------------------

class AgentStateDict(TypedDict, total=False):
    """TypedDict version of AgentState for LangGraph compatibility.

    LangGraph's StateGraph uses TypedDict for state schema. This mirrors
    AgentState's fields exactly. We convert between the two at graph
    entry/exit boundaries.
    """

    user_query: str
    filters: dict[str, Any]
    parsed_intent: Optional[dict[str, Any]]
    entities: dict[str, Any]
    execution_plan: list[str]
    validation: Optional[Any]
    rule_result: Optional[Any]
    ml_result: Optional[Any]
    risk_assessment: Optional[Any]
    graph_metrics: Optional[Any]
    explanation: Optional[str]
    recommendation: Optional[str]
    trace: list[str]
    errors: list[str]


# ---------------------------------------------------------------------------
# Conversion helpers
# ---------------------------------------------------------------------------

def state_to_dict(state: AgentState) -> dict[str, Any]:
    """Convert Pydantic AgentState to a plain dict for LangGraph."""
    return state.model_dump()


def dict_to_state(data: dict[str, Any]) -> AgentState:
    """Convert a LangGraph state dict back to a validated AgentState."""
    return AgentState.model_validate(data)
